[tool.poetry]
name = "ulauncher-fzf"
version = "0.1.0"
description = ""
authors = ["Hillary Chan <hillary.chan91@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
flake8 = "^4.0.1"
black = "^21.12b0"
isort = "^5.10.1"
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.messages_control]
disable= [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "line-too-long",
    "no-self-use",
    "too-few-public-methods",
    "too-many-arguments",
    "raise-missing-from",
    "fixme"
]

[tool.pylint.typecheck]
ignored-modules="ulauncher"
