name: ulauncher-fzf workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup poetry
        uses: snok/install-poetry@v1

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Install dependencies
        run: just setup

      - name: Run formatter checks
        run: just format-check

      - name: Run linter
        run: just lint
